# .docker_302/docker-compose302.yml
version: '3'
services:
  frontend:
    build:
      context: ..
      dockerfile: .docker_302/Dockerfile
    ports:
      - "3003:3000"  
    volumes:
      - ../app:/usr/src/app  
      - /usr/src/app/node_modules # anonymous volume