# .docker_202/docker-compose202.yml
version: '3'
services:
  frontend:
    build:
      context: ..
      dockerfile: .docker_202/Dockerfile
    ports:
      - "3002:3000"  # Map cổng 3000 trong container tới cổng 3002 trên host
    volumes:
      - ../app:/usr/src/app  # Mount thư mục app vào container
    networks:
      - shared-network

networks:
  shared-network:
    external: true
